apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ninetofiver
  name: ninetofiver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ninetofiver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: ninetofiver
    spec:
      containers:
        - args:
            - bash
            - -c
            - |2
                set -e
                python manage.py migrate
                echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin')" | python manage.py shell || true
                echo "from oauth2_provider.models import Application; from django.contrib.auth import get_user_model; User = get_user_model(); client = Application.objects.create(user=User.objects.filter(is_staff=True)[0], name='application', client_id='application-id', client_secret='application-secret', authorization_grant_type=Application.GRANT_PASSWORD)" | python manage.py shell || true
                python manage.py runserver 0.0.0.0:8000
          env:
            - name: CFG_FILE_PATH
              value: /etc/925r/config.yml
            - name: DJANGO_CONFIGURATION
              value: Dev
            - name: DJANGO_SETTINGS_MODULE
              value: ninetofiver.settings
            - name: MYSQL_DB
              value: ninetofiver-database
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              value: ninetofiver-password
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: ninetofiver-user
            - name: PYTHONDONTWRITEBYTECODE
              value: "1"
            - name: PYTHONUNBUFFERED
              value: "1"
          image: k3d-registry.localhost:5000/ninetofiver:latest
          name: ninetofiver
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
